# Конфигурация PteroStats
# Если вам нужна помощь, присоединяйтесь к нашему Discord-серверу здесь: https://discord.gg/zv6maQRah3

# Конфигурация бота
token: 'Поместите сюда токен бота'
presence:
    text: 'Панель хостинга'
    type: 'watching' # Может быть 'watch', 'playing', 'listening' или 'competing'. для 'streaming' пока не работает
    status: 'online' # Может быть 'online', 'idle', 'dnd' или 'invisible'

# Настройка канала Discord и времени обновления
channel: 'Поместите сюда идентификатор канала'
refresh: 60 # Через сколько времени бот будет обновлять статистику
timeout: 1 # Сколько времени ждать, пока нода ответит боту (если вы измените это значение, это добавит больше времени для обновления статистики).

# Конфигурация панели
panel:
    url: 'Поместите сюда URL панели'
    key: 'Поместите сюда API-ключ панели'

# Конфигурация сообщения и вложения
# оставьте '', если вы хотите отключить опцию
message:
    content: ''
    attachment: '' # Если вы включите функцию вложения в сообщение, оно сначала загрузит вложение перед отправкой или редактированием сообщения, что приведет к задержке статистики.

embed:
    title: 'PteroStats'
    color: '5865F2'
    description: 'Следующее обновление {{time}}' # Вы можете использовать {{time}}, чтобы сделать формат времени "через X секунд".
    footer: 'От Hirzi#8701 (перевод BlackRandomCraft#0001)'
    timestamp: true
    thumbnail: ''
    image: ''
    field:
        title: ''
        description: '' # Вы можете использовать {{time}}, чтобы сделать формат времени "через X секунд".

# Конфигурация кнопок сообщений
button:
    enable: true
    btn1:
        label: 'Оригинальный PteroStats'
        url: 'https://github.com/HirziDevs/PteroStats'
    btn2:
        label: 'Перевод PteroStats'
        url: 'https://github.com/ShieldNodes/PteroStats'
    btn3:
        label: ''
        url: ''
    btn4:
        label: ''
        url: ''
    btn5:
        label: ''
        url: ''

# Конфигурация статусного сообщения
# Как использовать пользовательские эмодзи: https://github.com/HirziDevs/PteroStats#using-custom-emoji
status:
    online: ':green_circle: Онлайн'
    offline: ':red_circle: Оффлайн'

# Настройка нод
# Как получить идентификатор ноды: https://github.com/HirziDevs/PteroStats#blacklist-nodes
nodes_settings:
    blacklist: [] # Вы можете добавить ID ноды, чтобы удалить ноду из статуса (Пример: "blacklist: [1]").
    details: false # Включить такие детали узла, как память и диск
    servers: true
    location: true
    allocations: true
    unit: 'gb' # Вы можете использовать " gb", "mb", "tb" или "percent".

# Настройки пользователей и серверов панели
panel_settings:
    status: true # Включить статистику панели в разделе статистики нод
    servers: true
    users: true

# Уведомляет пользователя или роль, если некоторые узлы находятся в автономном режиме (эта функция все еще тестируется, пожалуйста, сообщите, если у вас возникли проблемы).
mentions: # to enable atleast put 1 ID on user or role bellow
    user: [] # Поместите сюда идентификатор пользователя (Пример: "user: ['548867757517570058', '816219634390663230']")
    role: [] # Поместите сюда идентификатор роли (Пример: "role: ['796083838236622858', '858198863973187585']").
    channel: '' # Поместите сюда ID канала для протоколирования

# Запись ошибки в консоль, если сервер не в сети (включите эту функцию, если у вас есть проблема, о которой вы хотите сообщить)
log_error: false # Установите значение "true", чтобы включить